In [1]:
import torch
print(torch.accelerator)
torch.manual_seed(42)

<module 'torch.accelerator' from '/mnt/646AC6B66AC68470/Denoising_PoC/.venv/lib/python3.13/site-packages/torch/accelerator/__init__.py'>


In [2]:
image = torch.rand(6, 6)
print(image)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090]])


In [3]:
rates = image * 1000
print(rates)

tensor([[882.2693, 915.0040, 382.8638, 959.3057, 390.4482, 600.8953],
        [256.5725, 793.6414, 940.7715, 133.1859, 934.5981, 593.5797],
        [869.4044, 567.7153, 741.0941, 429.4045, 885.4429, 573.9045],
        [266.5800, 627.4492, 269.6317, 441.3636, 296.9208, 831.6855],
        [105.3149, 269.4948, 358.8126, 199.3638, 547.1916,   6.1604],
        [951.5546,  75.2659, 886.0137, 583.2096, 337.6477, 808.9750]])


In [4]:
rates_p = torch.poisson(rates)
print(rates_p)

tensor([[893., 861., 372., 865., 428., 583.],
        [244., 770., 951., 147., 917., 640.],
        [863., 560., 754., 442., 839., 554.],
        [272., 609., 263., 448., 306., 836.],
        [ 99., 276., 362., 182., 556.,   6.],
        [904.,  81., 886., 568., 343., 885.]])


In [5]:
image_p = rates_p / 1000
print(image_p)

tensor([[0.8930, 0.8610, 0.3720, 0.8650, 0.4280, 0.5830],
        [0.2440, 0.7700, 0.9510, 0.1470, 0.9170, 0.6400],
        [0.8630, 0.5600, 0.7540, 0.4420, 0.8390, 0.5540],
        [0.2720, 0.6090, 0.2630, 0.4480, 0.3060, 0.8360],
        [0.0990, 0.2760, 0.3620, 0.1820, 0.5560, 0.0060],
        [0.9040, 0.0810, 0.8860, 0.5680, 0.3430, 0.8850]])


In [6]:
torch.accelerator.current_accelerator()

device(type='cuda')